apiVersion: apps/v1
kind: Deployment
metadata:
  name: foyer-app
  labels:
    app: foyer-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: foyer-app
  template:
    metadata:
      labels:
        app: foyer-app
    spec:
      containers:
        - name: foyer-app
          image: ${registry}:${IMAGE_TAG}
          ports:
            - containerPort: 8080
          env:  # Add environment variables here
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://my-db:3306/tpFoyer17
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              value: root

---

apiVersion: v1
kind: Service
metadata:
  name: spring-boot-service
spec:
  type: NodePort
  selector:
    app: foyer-app
  ports:
    - protocol: TCP
      port: 8080           # Port sur lequel ton application écoute dans le conteneur
      targetPort: 8080      # Port exposé vers ton application
      nodePort: 30000       # Port exposé sur le nœud Kubernetes (entre 30000 et 32767)

# We can use a LoadBalancer Service instead, but it costs more
#  apiVersion: v1
#  kind: Service
#  metadata:
#    name: spring-boot-service
#  spec:
#    type: LoadBalancer
#    selector:
#      app: foyer-app
#    ports:
#      - protocol: TCP
#        port: 8080           # Port where your app listens inside the container
#        targetPort: 8080      # Port exposed to your application
