apiVersion: apps/v1
kind: Deployment
metadata:
  name: foyer-app
  labels:
    app: foyer-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: foyer-app
  template:
    metadata:
      labels:
        app: foyer-app
    spec:
      containers:
        - name: foyer-app
          image: fadyzaafrane/tpfoyer-17:latest
          ports:
            - containerPort: 8080