version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: my-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tpFoyer17
    ports:
      - "3306:3306"
    networks:
      - app-network
    volumes:
      - mysql-data:/var/lib/mysql

  springboot-app:
    image: ${registry}:${IMAGE_TAG}
    container_name: springboot-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/tpFoyer17
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      SERVER_PORT: 8080
    networks:
      - app-network
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react-frontend
    environment:
      - NODE_ENV=production
    networks:
      - app-network
    depends_on:
      - springboot-app

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/tmp/nginx.conf
    depends_on:
      - frontend
      - springboot-app
    networks:
      - app-network
    entrypoint: [ "/bin/sh", "-c", "cp /tmp/nginx.conf /etc/nginx/ && nginx -g 'daemon off;'" ]

networks:
  app-network:

volumes:
  mysql-data:
