apiVersion: v1
kind: Service
metadata:
  name: spring-boot-service
spec:
  type: NodePort
  selector:
    app: foyerApp
  ports:
    - protocol: TCP
      port: 8080           # Port sur lequel ton application écoute dans le conteneur
      targetPort: 8080      # Port exposé vers ton application
      nodePort: 30000       # Port exposé sur le nœud Kubernetes (entre 30000 et 32767)