apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "db.fullname" . }}
  labels:
    app: {{ include "db.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "db.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "db.name" . }}
    spec:
      containers:
        - name: {{ include "db.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: {{ .Values.mysql.rootPassword }}
            - name: MYSQL_DATABASE
              value: {{ .Values.mysql.database }}
          ports:
            - containerPort: {{ .Values.service.port }}
          # Uncomment the following lines if using persistent storage
          # volumeMounts:
          #   - name: mysql-data
          #     mountPath: /var/lib/mysql
      # Uncomment the following lines if using persistent storage
      # volumes:
      #   - name: mysql-data
      #     persistentVolumeClaim:
      #       claimName: {{ include "db.fullname" . }}-pvc
